from cave import Cave
from character import Character, Enemy

entrance = Cave("entrance")
cavern1 = Cave("cavern")
cavern2 = Cave("cavern")
grotto = Cave("grotto")
dungeon1 = Cave("dungeon")
dungeon2 = Cave("dungeon")
limestone = Cave("limestone cave")
treasury = Cave("treasury")
froom = Cave("friend room")
cliff1 = Cave("cliff")
cliff2 = Cave("cliff")
cliff3 = Cave("cliff")
cliff4 = Cave("cliff")
cliff5 = Cave("cliff")
cliff6 = Cave("cliff")
wumproom = Cave("wumpus room")
entrance.set_description("Dark and mossy stairs that only lead down.")
cavern1.set_description("A damp and dirty cave.")
cavern2.set_description("A damp and dirty cave.")
grotto.set_description("A small, dark and damp grotto.")
dungeon1.set_description("A dark and eerie dungeon.")
dungeon2.set_description("A dark and eerie dungeon.")
limestone.set_description("A cave with beautiful limestone formations.")
treasury.set_description("A cave filled empty chests, one stands out to you.")
froom.set_description("A room with a friendly creature.")
cliff1.set_description("A small cliff overlooking another area (usually one way).")
cliff2.set_description("A small cliff overlooking another area (usually one way).")
cliff3.set_description("A small cliff overlooking another area (usually one way).")
cliff4.set_description("A small cliff overlooking another area (usually one way).")
cliff5.set_description("A small cliff overlooking another area (usually one way).")
cliff6.set_description("A small cliff overlooking another area (usually one way).")
wumproom.set_description("A dark room with a wumpus lurking in the shadows.")
entrance.link_cave(grotto, "north")
cavern1.link_cave(cliff1, "west")
cavern1.link_cave(froom, "east")
cavern1.link_cave(cliff3, "south")
froom.link_cave(cavern1, "west")
froom.link_cave(cliff4, "south")
cliff1.link_cave(cavern1, "east")
cliff1.link_cave(cliff2, "south")
cliff1.link_cave(dungeon1, "west")
dungeon1.link_cave(cliff1, "east")
dungeon1.link_cave(wumproom, "south")
dungeon1.link_cave(limestone, "west")
limestone.link_cave(dungeon1, "east")
limestone.link_cave(treasury, "south")
treasury.link_cave(limestone, "north")
treasury.link_cave(dungeon2, "south")
cliff4.link_cave(froom, "north")
cliff4.link_cave(cliff5, "south")
cliff3.link_cave(cliff4, "east")
cliff3.link_cave(cliff2, "west")
cliff2.link_cave(cliff3, "east")
cliff2.link_cave(grotto, "south")
cliff5.link_cave(cliff6, "west")
cliff6.link_cave(cliff5, "east")
cliff6.link_cave(grotto, "west")
grotto.link_cave(cliff2, "north")
grotto.link_cave(cliff6, "east")
grotto.link_cave(cavern2, "west")
cavern2.link_cave(grotto, "east")
cavern2.link_cave(dungeon2, "west")
dungeon2.link_cave(cavern2, "east")
dungeon2.link_cave(treasury, "north")
harry = Enemy("Harry", "A smelly Wumpus")
harry.set_conversation("Hangry…Hanggrry")
harry.set_weakness("vegemite")
wumproom.set_character(harry)


current_cave = entrance          
while True:		
    print("\n")         
    current_cave.get_details()         
    command = input("> ")    
    current_cave = current_cave.move(command)  
